services:
  - type: web
    name: propertyguru
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --keep-alive 60 web_ui.app:app
    plan: free
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: ZAMEEN_CHROMA_PERSIST_DIR
        value: /app/data/chromadb_data
      - key: COHERE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: propertyguru-disk
      mountPath: /app/data
      sizeGB: 1