services:
  - type: web
    name: propertyguru
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python web_ui/app.py
    plan: free
    healthCheckPath: /health
    env:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
    envVars:
      - key: COHERE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: propertyguru-disk
      mountPath: /app/data
      sizeGB: 1